config/routes.rb
Rails.application.routes.draw do
  root "pages#home"
  get "diner", to: "pages#diner"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @projects = [
      { name: "FUN WITH LAW", url: "#", year: "2025", tech: "BackEnd+FrontEnd" }
    ]
  end

  def diner
    @projects = [
      { name: "FUN WITH LAW", url: "#", year: "2025", tech: "BackEnd+FrontEnd" }
    ]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Portfolio If" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>

app/views/pages/diner.html.erb
<body style= "background-image: url('<%= asset_path("grunge.png") %>');"class="bg-texture text-[#B0C4DE] font-sans tracking-wide">

  <nav class="fixed top-0 left-0 w-full z-50 flex justify-between text-sm uppercase">
    <div class="pl-6 py-6">
      <%= link_to "to Tokyo mode", root_path, data: { turbo: false }, class: "hover:underline font-bold" %>
    </div>

    <div class="space-x-8 pr-6 py-6">
      <button id="projects-link" class="hover:underline font-bold">PROJECTS</button>
      <button id="info-link" class="hover:underline font-bold">INFO</button>
      <button id="contact-link" class="hover:underline font-bold">CONTACT</button>
    </div>
  </nav>
      
  <div id="email-display" class="fixed top-[7rem] h-[calc(100vh-6rem)] w-1/3 max-w-sm p-6 opacity-0 transition-opacity duration-500 ease-in-out pointer-events-none text-base leading-relaxed text-[#B0C4DE] font-bold">
    <a href="mailto:ines.fevrier@gmail.com" class="underline">ines.fevrier@gmail.com</a>
  </div>
  
  <div id="bio-display" 
     class="fixed top-[7rem] h-[calc(100vh-6rem)] w-1/3 max-w-sm p-6 opacity-0 transition-opacity duration-500 ease-in-out pointer-events-none text-base leading-relaxed text-[#B0C4DE] font-semibold">
      <p class="mb-4">
        Problem solver, lego builder, urban landscapes inspired. Fullstack. Now, let's talk about your projects and how to give them life. 
      </p>
  </div>
  
  <div id="projects-display" class="fixed top-[7rem] left-6 h-[calc(100vh-6rem)] w-1/3 max-w-sm p-6 opacity-0 transition-opacity duration-500 ease-in-out pointer-events-none text-3xl leading-relaxed text-[#B0C4DE] font-bold space-y-2">
    <% @projects.each do |project| %>
      <%= link_to project[:name], project[:url], target: "_blank", class: "underline block" %>
        <div class="text-sm font-light">
          <%= project[:year]%>/<%= project[:tech]%>
        </div>
    <% end %>
  </div>
  
  <section class="min-h-screen flex items-center justify-start pl-14">
    <div class="text-center space-y-6">
      <h1 class="text-5xl font-bold uppercase text-[#B0C4DE] tracking-widest">Inès Février</h1>
      <p class="text-2xl font-bold uppercase text-[#B0C4DE]">Web Developer</p>
    </div>
  </section>
  
  <script>
    document.addEventListener("turbo:load", () => {
      const emailDisplay = document.getElementById("email-display");
      const contactLink = document.getElementById("contact-link");
      const bioDisplay = document.getElementById("bio-display");
      const projectsDisplay = document.getElementById("projects-display");
      const projectsLink = document.getElementById("projects-link");

      if (emailDisplay && projectsLink) {
        emailDisplay.classList.remove("opacity-100", "pointer-events-auto");
        emailDisplay.classList.add("opacity-0", "pointer-events-none");
        const rect = projectsLink.getBoundingClientRect();
        const offset = 23;
        emailDisplay.style.left = `${rect.left - offset}px`;
        emailDisplay.style.top = '3.5rem';
        emailDisplay.style.width = '20rem';
      }
  
      if (bioDisplay && projectsLink) {
        bioDisplay.classList.remove("opacity-100", "pointer-events-auto");
        bioDisplay.classList.add("opacity-0", "pointer-events-none");
        const rect = projectsLink.getBoundingClientRect();
        const offset = 23;
        bioDisplay.style.left = `${rect.left - offset}px`;
        bioDisplay.style.top = '3.5rem';
        bioDisplay.style.width = '20rem';
      }

      if (projectsDisplay && projectsLink) {
        projectsDisplay.classList.remove("opacity-100", "pointer-events-auto");
        projectsDisplay.classList.add("opacity-0", "pointer-events-none");
        const rect = projectsLink.getBoundingClientRect();
        const offset = 23;
        projectsDisplay.style.left = `${rect.left - offset}px`;
        projectsDisplay.style.top = '3.5rem';
        projectsDisplay.style.width = '20rem';
      }
   } );

    document.addEventListener("click", (event) => {
      const emailDisplay = document.getElementById("email-display");
      const bioDisplay = document.getElementById("bio-display");
      const projectsDisplay = document.getElementById("projects-display");

      if (!emailDisplay || !bioDisplay || !projectsDisplay) return;

      const target = event.target.closest("a, button");
      if (!target) return;

      if (target.id === "contact-link") {
        event.preventDefault();
        const isVisible = emailDisplay.classList.contains("opacity-100");

        if (isVisible) {
          emailDisplay.classList.remove("opacity-100", "pointer-events-auto");
          emailDisplay.classList.add("opacity-0", "pointer-events-none");
        } 
        else {
          emailDisplay.classList.remove("opacity-0", "pointer-events-none");
          emailDisplay.classList.add("opacity-100", "pointer-events-auto");
        }

        bioDisplay.classList.remove("opacity-100", "pointer-events-auto");
        bioDisplay.classList.add("opacity-0", "pointer-events-none");

        projectsDisplay.classList.remove("opacity-100", "pointer-events-auto");
        projectsDisplay.classList.add("opacity-0", "pointer-events-none");
      }

      if (target.id === "info-link") {
        event.preventDefault();
        const isVisible = bioDisplay.classList.contains("opacity-100");

        if (isVisible) {
          bioDisplay.classList.remove("opacity-100", "pointer-events-auto");
          bioDisplay.classList.add("opacity-0", "pointer-events-none");
        } 
        else {
          bioDisplay.classList.remove("opacity-0", "pointer-events-none");
          bioDisplay.classList.add("opacity-100", "pointer-events-auto");
        }

        emailDisplay.classList.remove("opacity-100", "pointer-events-auto");
        emailDisplay.classList.add("opacity-0", "pointer-events-none");

        projectsDisplay.classList.remove("opacity-100", "pointer-events-auto");
        projectsDisplay.classList.add("opacity-0", "pointer-events-none");
      }

      if (target.id === "projects-link") {
        event.preventDefault();
        const isVisible = projectsDisplay.classList.contains("opacity-100");

        if (isVisible) {
            projectsDisplay.classList.remove("opacity-100", "pointer-events-auto");
          projectsDisplay.classList.add("opacity-0", "pointer-events-none");
        } 
        else {
          projectsDisplay.classList.remove("opacity-0", "pointer-events-none");
          projectsDisplay.classList.add("opacity-100", "pointer-events-auto");
        }

        emailDisplay.classList.remove("opacity-100", "pointer-events-auto");
        emailDisplay.classList.add("opacity-0", "pointer-events-none");

        bioDisplay.classList.remove("opacity-100", "pointer-events-auto");
        bioDisplay.classList.add("opacity-0", "pointer-events-none");
      }
    } );
  </script>
</body>

app/views/pages/home.html.erb
<body style= "background-image: url('<%= asset_path("asfalt.png") %>');" class="bg-texture text-gray-800 font-sans tracking-wide">

  <nav class="fixed top-0 left-0 w-full z-50 flex justify-between text-sm uppercase">
    <div class="pl-6 py-6">
      <%= link_to "to Diner mode", diner_path, data: { turbo: false }, class: "hover:underline font-bold" %>
    </div>

    <div class="space-x-8 pr-6 py-6">
      <button id="projects-link" class="hover:underline font-bold">PROJECTS</button>
      <button id="info-link" class="hover:underline font-bold">INFO</button>
      <button id="contact-link" class="hover:underline font-bold">CONTACT</button>
    </div>
  </nav>
      
  <div id="email-display" class="fixed top-[7rem] h-[calc(100vh-6rem)] w-1/3 max-w-sm p-6 opacity-0 transition-opacity duration-500 ease-in-out pointer-events-none text-base leading-relaxed text-gray-800 font-bold">
    <a href="mailto:ines.fevrier@gmail.com" class="underline">ines.fevrier@gmail.com</a>
  </div>
  
  <div id="bio-display" 
     class="fixed top-[7rem] h-[calc(100vh-6rem)] w-1/3 max-w-sm p-6 opacity-0 transition-opacity duration-500 ease-in-out pointer-events-none text-base leading-relaxed text-gray-800 font-semibold">
      <p class="mb-4">
        Problem solver, lego builder, urban landscapes inspired. Fullstack. Now, let's talk about your projects and how to give them life. 
      </p>
  </div>
  
  <div id="projects-display" class="fixed top-[7rem] left-6 h-[calc(100vh-6rem)] w-1/3 max-w-sm p-6 opacity-0 transition-opacity duration-500 ease-in-out pointer-events-none text-3xl leading-relaxed text-gray-800 font-bold space-y-2">
    <% @projects.each do |project| %>
      <%= link_to project[:name], project[:url], target: "_blank", class: "underline block" %>
        <div class="text-sm font-light text-gray-700">
          <%= project[:year]%>/<%= project[:tech]%>
        </div>
    <% end %>
  </div>
  
  <section class="min-h-screen flex items-center justify-start pl-14">
    <div class="text-center space-y-6">
      <h1 class="text-5xl font-bold uppercase text-gray-800 tracking-widest">Inès Février</h1>
      <p class="text-2xl font-bold uppercase text-gray-800">Web Developer</p>
    </div>
  </section>
  
  <script>
    document.addEventListener("turbo:load", () => {
      const emailDisplay = document.getElementById("email-display");
      const contactLink = document.getElementById("contact-link");
      const bioDisplay = document.getElementById("bio-display");
      const projectsDisplay = document.getElementById("projects-display");
      const projectsLink = document.getElementById("projects-link");

      if (emailDisplay && projectsLink) {
        emailDisplay.classList.remove("opacity-100", "pointer-events-auto");
        emailDisplay.classList.add("opacity-0", "pointer-events-none");
        const rect = projectsLink.getBoundingClientRect();
        const offset = 23;
        emailDisplay.style.left = `${rect.left - offset}px`;
        emailDisplay.style.top = '3.5rem';
        emailDisplay.style.width = '20rem';
      }
  
      if (bioDisplay && projectsLink) {
        bioDisplay.classList.remove("opacity-100", "pointer-events-auto");
        bioDisplay.classList.add("opacity-0", "pointer-events-none");
        const rect = projectsLink.getBoundingClientRect();
        const offset = 23;
        bioDisplay.style.left = `${rect.left - offset}px`;
        bioDisplay.style.top = '3.5rem';
        bioDisplay.style.width = '20rem';
      }

      if (projectsDisplay && projectsLink) {
        projectsDisplay.classList.remove("opacity-100", "pointer-events-auto");
        projectsDisplay.classList.add("opacity-0", "pointer-events-none");
        const rect = projectsLink.getBoundingClientRect();
        const offset = 23;
        projectsDisplay.style.left = `${rect.left - offset}px`;
        projectsDisplay.style.top = '3.5rem';
        projectsDisplay.style.width = '20rem';
      }
   } );

    document.addEventListener("click", (event) => {
      const emailDisplay = document.getElementById("email-display");
      const bioDisplay = document.getElementById("bio-display");
      const projectsDisplay = document.getElementById("projects-display");

      if (!emailDisplay || !bioDisplay || !projectsDisplay) return;

      const target = event.target.closest("a, button");
      if (!target) return;

      if (target.id === "contact-link") {
        event.preventDefault();
        const isVisible = emailDisplay.classList.contains("opacity-100");

        if (isVisible) {
          emailDisplay.classList.remove("opacity-100", "pointer-events-auto");
          emailDisplay.classList.add("opacity-0", "pointer-events-none");
        } 
        else {
          emailDisplay.classList.remove("opacity-0", "pointer-events-none");
          emailDisplay.classList.add("opacity-100", "pointer-events-auto");
        }

        bioDisplay.classList.remove("opacity-100", "pointer-events-auto");
        bioDisplay.classList.add("opacity-0", "pointer-events-none");

        projectsDisplay.classList.remove("opacity-100", "pointer-events-auto");
        projectsDisplay.classList.add("opacity-0", "pointer-events-none");
      }

      if (target.id === "info-link") {
        event.preventDefault();
        const isVisible = bioDisplay.classList.contains("opacity-100");

        if (isVisible) {
          bioDisplay.classList.remove("opacity-100", "pointer-events-auto");
          bioDisplay.classList.add("opacity-0", "pointer-events-none");
        } 
        else {
          bioDisplay.classList.remove("opacity-0", "pointer-events-none");
          bioDisplay.classList.add("opacity-100", "pointer-events-auto");
        }

        emailDisplay.classList.remove("opacity-100", "pointer-events-auto");
        emailDisplay.classList.add("opacity-0", "pointer-events-none");

        projectsDisplay.classList.remove("opacity-100", "pointer-events-auto");
        projectsDisplay.classList.add("opacity-0", "pointer-events-none");
      }

      if (target.id === "projects-link") {
        event.preventDefault();
        const isVisible = projectsDisplay.classList.contains("opacity-100");

        if (isVisible) {
            projectsDisplay.classList.remove("opacity-100", "pointer-events-auto");
          projectsDisplay.classList.add("opacity-0", "pointer-events-none");
        } 
        else {
          projectsDisplay.classList.remove("opacity-0", "pointer-events-none");
          projectsDisplay.classList.add("opacity-100", "pointer-events-auto");
        }

        emailDisplay.classList.remove("opacity-100", "pointer-events-auto");
        emailDisplay.classList.add("opacity-0", "pointer-events-none");

        bioDisplay.classList.remove("opacity-100", "pointer-events-auto");
        bioDisplay.classList.add("opacity-0", "pointer-events-none");
      }
    } );
  </script>
</body>